cc_library(
  name = "binary_search_tree",
  hdrs = glob([
    "*.hpp",
    "iterators/*.hpp"
  ]),
  includes = ["include"],
  copts = [
    "-Iinclude/",
    "-std=c++17",
    "-Wno-deprecated"
  ],
  visibility = [
    "//visibility:public"
  ]
)
