filegroup(
  name = "examples",
  srcs = [
    "//examples/insertion:insertion",
    "//examples/removal:removal",
    "//examples/search:search",
    "//examples/using_other_types:using_other_types"
  ]
)