cc_binary(
  name = "search",
  srcs = ["main.cpp"],
  copts = [
    "-Iinclude",
    "-std=c++17",
    "-Wno-deprecated"
  ],
  deps = [
    "//include:binary_search_tree"
  ],
  visibility = ["//visibility:public"]
)
